import Provider from "@/app/_trpc/Provider";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <Theme appearance="dark">
          <Provider>
            <div vaul-drawer-wrapper="">{children}</div>
          </Provider>
        </Theme>
      </body>
    </html>
  );
}
